[package]
name = "car"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2.0.60", features = ["full", "extra-traits"] }
quote = "1.0.36"
anyhow = "1.0.82"
sha1 = "0.10.6"
